[
  {
    "set": "cksum",
    "id": 1,
    "messages": [
      {
        "msg": "file_read_error",
        "id": 1,
        "description": "We were unable to read from file {0}.  Errno is {1}, and the string message related to it is {2}.",
        "C": "Unable to read from '{0}'.  Error code {1}: {2}"
      },
      {
        "msg": "file_open_error",
        "id": 2,
        "description": "We were unable to open the file called {0}.  Errno is {0}, and the string message related to it is {1}.",
        "C": "Unable to open the file '{0}'.  Error code {1}: {2}"
      },
      {
        "msg": "stdin_name",
        "id": 3,
        "description": "The display name for standard input",
        "C": "(standard input)"
      },
      {
        "msg": "unhandled_std_exception",
        "id": 4,
        "description": "We were caught an exception of type std::exception, with a what() of {0}.",
        "C": "Unhandled exception: {0}"
      },
      {
        "msg": "unhandled_exception",
        "id": 5,
        "description": "We were caught an exception of unknown type.",
        "C": "Unhandled exception."
      }
    ]
  }
]
